docker/ssh/Dockerfile
Add Dockerfile in docker/ssh with openssh server installed.
Add kernelci user in ssh/Dockerfile.
=> docker/ssh : Add SSH container

.github/workflows/main.yml, docker/api/Dockerfile
Use Python 3.10 rather than 3.8 for the KernelCI API container as all
the components are compatible.  Extend the GitHub checks to Python
3.10 as well.
=> docker: use Python 3.10 for the API container

api/main.py, api/pubsub.py
Add PubSub.publish_cloudevent() method and move the cloudevent
wrapping code from api.main to api.pubsub.  This will allow other
parts of the code to generate CloudEvents by using api.pubsub
directly.
=> api.pubsub: add .publish_cloudevent() method

api/main.py, api/pubsub.py
Add unique IDs for each Pub/Sub subscription rather than rely on user / channel combinations.  The IDs are managed with an int stored in Redis.
Fixes #26
=> T31494 Pub/Sub IDs

api/main.py
Deal with API calls that set the token value to 'None' by returning
HTTP 401.  This may happen by converting a None object to a string on
the client side, and it will then get converted to a NoneType object
on the API side and cause an exception in oauth2_scheme.
=> api.main: deal with 'None' token

api/auth.py
The Authentication.get_current_user() method does a database query
which is asynchronous.  As such, declare the method as async and use
await when quering the database.
=> api.auth: fix async call to .get_current_user()

api/db.py
The objects passed to Database.create() always have a .id attribute as
it's defined in the Pydantic models.  However, it should be None in
the case of a new object since it hasn't been saved in the database
yet.  As such, fix the check to only create objects when the .id is
None.
Fixes: 54f51945e591 ("api: add api.db.Database() abstraction class")
=> api.db: fix obj.id check

api/db.py, api/main.py, api/models.py
Add minimal Node object model with the ability to update them in the database.  Generate events whenever a Node object is created or updated.
The Node model has an optional boolean `status` field to contain the result of the step.  It is set to `None` by default, which means the result is still pending.  Then typically `True` means it passed and `False` means it failed.
Fixes #25
=> T31493 node model

api/models.py
Add .url and .describe fields to the Revision model, to contain the
Git URL and Git describe strings.  This should help align with the
current bmeta.json schema used by kernelci-core.
Part of #37
=> api.models: add Revision.url and .describe

docker/docker-compose.yaml
Added docker volume for mongodb.
=> docker/docker-compose.yaml : Add fix for mongodb container on WSL

.github/workflows/main.yml
Fixes https://github.com/kernelci/kernelci-api/issues/44
.github/workflows/main.yml: Added steps to run pytest for kernelci-api
api/__init__.py: Add file to make api a package
api/test_api.py: Add file with root endpoint test case
docker/api/requirements-dev.txt: Add file with python test packages
=> Run kernelci-api test with Github Actions

api/test_api.py, docker/api/requirements-dev.txt
Fixes https://github.com/kernelci/kernelci-api/issues/47
api/test_api.py: Add test case for token endpoint
docker/api/requirements-dev.txt: Add pytest-mock
=> API unit test case for /token endpoint

.github/workflows/main.yml, README.md, docker/api/installPackagesDev.sh, docker/api/installPackagesProduction.sh, docker/api/requirements-dev.txt
Use `actions/setup-python` to install the actual Python version required, and reduce to only testing with Python 3.10 as it's the only version that actually works with all the current requirements.  Also consolidate how requirements-dev.txt is used to simplify things.
=> Fix GitHub actions running checks

.github/workflows/main.yml, api/models.py, docker/api/requirements-dev.txt
Add a check in the GitHub actions to run Pylint on `api.models` and fix all the errors reported by it so the score is 10.0.  Ignore warnings about the number of public methods on classes as model classes don't have any methods by design.
Other modules in the `api` package should be added as a follow-up in the same way.
=> Run Pylint on api.models using GitHub actions

docker/api/Dockerfile, docker/docker-compose.yaml
Add a build argument ${REQUIREMENTS} which defaults to
requirements.txt but can be overridden by an environment variable at
build time to specify an alternative requirements file.  For example,
to start docker-compose with the development tools installed in the
API container:
REQUIREMENTS=requirements-dev.txt docker-compose up --build
=> docker: add REQUIREMENTS build argument

README.md, docker-compose.yaml
Move the docker-compose.yaml file to the root directory of the project
so it can be used more easily.  This makes it more consistent with
kernelci-pipeline too.  Update the README.md accordingly.
=> docker: move docker-compose.yaml file to root directory

api/test_api.py
Fixes https://github.com/kernelci/kernelci-api/issues/67
Negative testing of /token endpoint by providing incorrect
password.
=> api/test_api.py: Add /token endpoint test for negative path

api/test_api.py
Fixes: https://github.com/kernelci/kernelci-api/issues/68
api/test_api.py: Add fixture to mock PubSub._init_sub_id
api/test_api.py: Add fixture to mock PubSub.subscribe
api/test_api.py:  Add test_subscribe_endpoint
=> api/test_api.py: Add /subscribe endpoint test

api/test_api.py
Fixes https://github.com/kernelci/kernelci-api/issues/69
Test case for /unsubscribe endpoint for the positive path
Test case for /unsubscribe endpoint for the negative path
=> api/test_api.py: Add test cases for /unsubscribe endpoint

api/test_api.py
Fixes https://github.com/kernelci/kernelci-api/issues/77
api/test_api.py: Add fixture to mock Database.create
api/test_api.py: Add fixture to mock PubSub.publish_cloudevent
api/test_api.py: Add test_create_node_endpoint to test POST /node endpoint
=> Add test case to create node object

api/test_api.py
Fixes https://github.com/kernelci/kernelci-api/issues/81
api/test_api.py: Add fixture for Database.find_by_attributes
api/test_api.py: Add test_get_node_by_attributes_endpoint_positive
api/test_api.py: Add test_get_node_by_attributes_endpoint_negative
=> Add test case to get nodes by attributes

api/test_api.py
Fixes https://github.com/kernelci/kernelci-api/issues/79
api/test_api.py: Add fixture for Database.find_by_id
api/test_api.py: Add test_get_node_by_id_endpoint_positive
api/test_api.py: Add test_get_node_by_id_endpoint_negative
=> Add test for get node by ID endpoint

api/test_api.py
Fixes https://github.com/kernelci/kernelci-api/issues/83
api/test_api.py: Add test_get_all_nodes_positive
api/test_api.py: Add test_get_all_nodes_negative
=> Add test case for /nodes endpoint

api/test_api.py
Fixes https://github.com/kernelci/kernelci-api/issues/92
api/test_api.py: fix assertion in test_get_node_by_id_endpoint
api/test_api.py: fix assertion in test_token_endpoint
api/test_api.py: fix assertion in test_create_node_endpoint
api/test_api.py: fix assertion in test_subscribe_endpoint
api/test_api.py: fix assertion in test_me_endpoint
=> Fix test assertions in test_api.py

README.md
/nodes endpoint returns a list of Node objects.
Hence, modified description in README.md accordingly.
Fixes: cdcf8b8 ("README.md: Replace 'Things' section with 'Nodes'")
=> Fix 'Node' description in README.md

api/pubsub.py
Fix warning:
api/pubsub.py:52: RuntimeWarning: coroutine 'PubSub.execute_command'
was never awaited :sub.unsubscribe()
=> api/pubsub.py: use 'await' with aioredis unsubscribe() call

test/test_me_handler.py, test/test_node_handler.py, test/test_root_handler.py, test/test_subscribe_handler.py, test/test_token_handler.py, test/test_unsubscribe_handler.py
Move related test cases from api/test_api.py to
various files under test directory.
=> test: split test cases defined in api/test_api.py

test/test_pubsub.py
Fixes https://github.com/kernelci/kernelci-api/issues/91
test/test_pubsub.py: Add test_unsubscribe_sub_id_not_exists test case
test/test_pubsub.py: Add test_unsubscribe_sub_id_exists test case
test/test_pubsub.py: Add mock_pubsub_subscriptions fixture
=> Add tests for api.pubsub.PubSub.unsubscribe()

api/models.py
trigger script from the kernelci-pipeline will post
a new node with an empty Revision.describe property.
When a new revision is available, the client will
update the revision information with the git describe.
Fixes: 15380ac ("api.models: add Revision.url and .describe")
=> api/models.py: modify Revision.describe to be Optional

docker-compose.yaml
Fixes https://github.com/kernelci/kernelci-api/issues/29
docker-compose.yaml: Add parameters for host port numbers
=> Add docker-compose parameters for port numbers

api/test_api.py
Fixes #70 
Include listen endpoint test cases for positive and negative cases, respectively with answers 200 and 404.
Signed-off-by: Alexandra Pereira <alexandra.pereira@collabora.com>
=> api/test_api.py:add test cases for listen endpoint

api/pubsub.py
Fixes https://github.com/kernelci/kernelci-api/issues/40
Define 'redis_host' and 'redis_database_number' in Settings class.
Use redis options from Settings class in the PubSub constructor.
=> api/pubsub.py: add redis option to Settings class

api/models.py, test/test_node_handler.py
Add optional artifacts dictionary to the Node model as a mapping
between names and URLs to download files from the storage.
=> api.models.Node: add artifacts

test/test_node_handler.py
'request_dict' is not being used in test_get_node_by_id_endpoint_empty_response.
Remove unnecessary code from the test function.
Fixes c933034 api/test_api.py: Add test_get_node_by_id_endpoint_empty_response
=> test/test_node_handler: Remove 'request_dict' from a test case

api/main.py, api/pubsub.py, test/test_listen_handler.py, test/test_pubsub.py, test/test_unsubscribe_handler.py
Raise a `ValueError` exception when the subscription id is not valid.
=> Pub/Sub: raise exceptions when invalid id

docker-compose.yaml
Add a bind-mount volume with the 'test' directory to the api container
so unit tests can be run in the same environment.  To run the unit
tests by hand, one can now do:
$ REQUIREMENTS=requirements-dev.txt docker-compose build
$ docker-compose run api pytest test
=> docker-compose.yaml: bind-mount volume with tests

README.md
Fixes https://github.com/kernelci/kernelci-api/issues/115
Need to have certain file permissions to be able to login
to kernelci-ssh container using SSH authorization keys.
Need to change file permissions on WSL setup.
=> README.md: add section for SSH login on WSL

.gitignore
Add the ssh user-data and storage data directories to .gitignore as
they contain data files which should not be kept under source control.
=> gitignore: add ssh and storage data directories

docker-compose.yaml
Use kernelci-api as a prefix in all the container names so they can be
listed and filtered more easily while running other services on the
same host.
=> docker-compose.yaml: use kernelci-api prefix in container names

api/pubsub.py
Disable the keep-alive feature by default using a value of 0 since
it's only needed in particular cases such as behind a proxy or
firewall monitoring the connection's activity.
=> api.pubsub: disable keep-alive with default value of 0

doc/_index.md, doc/overview.md
Add an overview section in the documentation.
On staging: https://static.staging.kernelci.org/docs/api/
=> T33705 doc: add API and pipeline overview

api/main.py, api/models.py, doc/getting-started.md
Convert the `/hash` endpoint to use `POST` method so the plaintext passwords aren't sent as part of the URL.
=> Convert `/hash` to `POST`

test/test_node_handler.py
Modify status value according to the new schema.
Change it from None to default "pending" in
test_get_root_node_endpoint test case.
Fixes: c3d7af4 ("test/test_node_handler: Add 'test_get_root_node_endpoint")
=> test/test_node_handler: fix Node.status value

test/test_node_handler.py
Add Node attributes to request params in
'test_get_nodes_by_attributes_endpoint' test case.
Rename test cases related to 'nodes/' as multiple
nodes are being returned.
=> test_node_handler.py: add request params for 'nodes/' tests

api/auth.py
We can remove the class as it was just
being used for getting token associated username,
which we can get anyway in auth.get_current_user
without using the class.
=> T35340 api/auth.py: drop TokenData class

test/conftest.py, test/test_user_handler.py
Depends on https://github.com/kernelci/kernelci-api/pull/140
Develop tests for /user endpoint for the positive and negative paths.
=> T35357 Implement unit tests for  /user endpoint

test/conftest.py, test/test_token_handler.py, test/test_user_handler.py
Depends on https://github.com/kernelci/kernelci-api/pull/143
Unit test for /token endpoint to get token with admin scope for Admin user.
=> T35393 Add unit test for /token endpoint for Admin

api/main.py
Fix `CryptContext.verify` failing with the correct username and password. Need to use `get_secret_value()`
to get password in plain text while getting hash from password of type `SecretStr`.
=> T35960 Fix authorization issue

doc/api-details.md, doc/getting-started.md
Add instructions for adding users using `/user` endpoint.
Also, add description for getting token for an admin user.
=> T35622 API: Add documentation for admin user

doc/api-details.md, doc/getting-started.md
Update the getting-started section to start by creating an admin user.
Then an extra step could be added as a follow-up to create regular
users via kci_data.
The tools to create API tokens and to create the initial user should
probably be improved first to simplify these initial steps before
adding more instructions (tool to just ask for admin password and
create entry + API token automatically etc.).
=> doc: create admin user in getting-started section

create_admin_user
A python script, used to create a very first admin user by providing username, password, and optional API host URL from the command line.
After that a token can be retrieved to create other users using `/user` endpoint.
=> T35921 Command line utility to create an admin user

doc/getting-started.md
Update the "Getting Started" page with a sample command using the new
create_admin_user script to create an initial admin user account
instead of raw HTTP queries.
=> doc: update getting started page with create_admin_user

api/models.py
Add a KernelVersion model and include it in Revision to store the
Linux kernel version information.
=> api.models: add KernelVersion to Revision

api/models.py
Node.status value 'complete' is more appropriate
than 'completed' to denote completed node.
=> T36848 api.models: rename Node status to 'complete'

api/main.py, api/models.py
Need to remove method and logic to set node status
to timeout in '/trigger_completed_event' endpoint
as a separate client script will be used
to do so in pipeline.
Fixes: 2e3c506 ("api.main: Add 'trigger_completed_event' endpoint")
=> T35078 api: drop Node.set_timeout_status, trigger_completed_event handler

api/models.py
Need to drop the method to wait for node
to get completed as it is not required
anymore as per the new design changes.
=> T35078 api.models: remove Node.wait_for_node method

api/db.py, api/main.py, api/models.py, test/conftest.py
Create an index on `User` model to make sure that the `username` is unique for every user.
=> T36032 User.username should be unique

api/main.py
Use `main.get_password_hash` instead of
`auth.get_password_hash` directly to convert
password from SecretStr to plain text first.
Fixes: 7a67489 ("api/main.py: implement /user endpoint")
=> api.main: fix user authentication

api/models.py, doc/overview.md, test/test_node_handler.py
Replace Node.status with Node.state to make it clear it's about the
state of the Node and not about any pass/fail result.  Update the list
of states to match the new specs.
=> api.models: implement new Node.state values

doc/api-details.md
Add a state diagram for Node objects.  Also clean up and improve some parts of the api-details page.
=> Add Node state diagram

api/main.py, api/models.py, api/paginator_models.py, docker/api/requirements.txt, test/test_node_handler.py
Add 'skip' and 'limit' request query parameters to get a desired set of nodes in response from the endpoint.
Need to drop them from 'query_params' dictionary to match the fields with the model. It is required to get objects matching model attributes from the database.
=> T36916 Implement pagination for '/nodes' endpoint

api/db.py, api/main.py, api/models.py
Add a Hierarchy model and an entry point for submitting a hierarchy of nodes to be added with an existing root node as the top-level parent.  Implement a `Database.create_hierarchy()` method to create all the node objects in the database accordingly.
=> Add /nodes/{node_id} entry point for submitting hierarchy

api/models.py, test/test_node_handler.py
Rename the Node field `max_wait_time` to
`timeout` to be more appropriate.
=> api.models: rename Node.max_wait_time

api/models.py
Allow only default value for 'Node.kind' i.e 'node'.
This is required to get all the node objects based on the kind specified e.g regression nodes will have kind 'regression'.
=> T36501 Declare Node.kind to be constant

api/db.py, api/main.py, test/test_node_handler.py
Fixes https://github.com/kernelci/kernelci-api/issues/176
api.db: use pagination in `Database.find_by_attributes`
api.main: Drop the call to `paginate` method from `get_nodes`
=> T37711 Fix pagination integration with Mongo DB

api/main.py, api/models.py
Validate values of `Node.status` and `Node.result` before updating the node object.
=> T36483 Validate node transition

doc/api-details.md
Add a section to provide intructions on how to
use `/count` endpoint to get count of nodes.
=> doc/api-details: add `Getting Nodes count` section

api/main.py, api/models.py
Need to handle a case where node update operation
do not change the node state.
Fixes: 1f96e91 ("api.models: implement `Node.validate_node_transition`")
=> T38131 api.models: fix node state validation

api/main.py, api/models.py
Implement a method to check if the node is available to create child nodes. This is needed to avoid the creation of child nodes if the parent is still running or closing.
=> T38061 Validate parent in POST node handler

api/db.py, api/models.py
Instead of calculating expiry timestamp from
`Node.timeout` field to check whether the node
needs to change its state to `done`, directly
store expiry timestamp to the field using
`Node.set_timeout` method.
=> T37965 models: store node expiry timestamp to `Node.timeout`

api/models.py
Considering the possibility of skipped tests with certain test suite (for instance, fstests) we need to add `Node.result` value for it.
We also need to add a result value to denote node timeout.
As a result, we need to add 'SKIP' and 'INCOMPLETE' values to `ResultValues` to denote skipped tests and incompleted nodes respectively.
=> T36848 api.models: add 'SKIP' and 'INCOMPLETE' node result

api/db.py, api/models.py
Fixes https://github.com/kernelci/kernelci-api/issues/194
Fix error "AttributeError: 'User' object has no attribute 'set_timeout'" when trying to create new users using `/user` endpoint.
Need to add method `set_timeout` to `DatabaseModel` to fix `/user` endpoint failure. The `set_timeout` is being invoked while creating models in
`Database.create`. Hence, need to add it to the
parent class of `User` to fix the issue.
Fixes: 98db8b3 ("db: set timeout upon node creation")
=> T38595 api.models: fix `/user` endpoint failure

api/db.py, api/models.py
Rather than implicitly setting the timeout to a fixed value in the `Database` class, set a default value of 6h in the Node base model and allow the user to set it to any arbitrary value.  Also drop the `Optional` hints for mandatory fields including `timeout`.
=> Fix timeout value handling in API

doc/api-details.md, docker-compose.yaml, docker/api/requirements.txt, migrations/20221014061654_set_timeout.py
- Since the `timeout` field is updated to store the node expiry timestamp, need to add a migration file to update existing Node objects.
- Use `pymongo-migrate` package to implement schema migration mechanism.
- Mount `migrations` volume to api container.
- Add command to run migrations on api container startup.
=> T38189 Add support for schema migrations

doc/api-details.md
Add information about request query params with comparison operator for `/nodes` and `/count` endpoints.
Also, add a note about field name restrictions.
=> T39454 doc/api-details: document comparison operators for request query params

api/main.py, api/models.py, doc/api-details.md
Fixes https://github.com/kernelci/kernelci-api/issues/205
Enable support for allowing `null` as the request query param value to `/nodes` and `/count` endpoints for GET requests.
e.g. Request to get root nodes from the database will be http://localhost:8001/nodes?parent=null
=> T39710 Query nodes with null field values

api/main.py, docker/api/requirements.txt, test/conftest.py, test/test_count_handler.py, test/test_listen_handler.py, test/test_me_handler.py, test/test_node_handler.py, test/test_root_handler.py, test/test_subscribe_handler.py, test/test_token_handler.py, test/test_unsubscribe_handler.py, test/test_user_handler.py
Fixes https://github.com/kernelci/kernelci-api/issues/208
Integrate `fastapi-versioning` module for versioning.
Use versioned FastAPI instance for API versioning by using `VersionedFastAPI`.
Provide version format (only major numbers at the moment) and prefix (i.e. `/v`) to the constructor.
Also, provide start-up handlers and default version i.e `v0`. The latest version can be called using `/latest` prefix.
Sample URL to get all the nodes: `https://API_SERVER_URL:PORT/v0/nodes`.
=> T39784 Introduce API versioning

api/main.py, api/models.py
Instead of returning `is_valid` flag and message from `validate_params`, raise `ValueError` if invalid state, result, or parent is received in the request query params.
Dropped mechanism to check the validation flag and move the method to try-except block to catch ValueError exceptions in `get_nodes` and `get_nodes_count` handlers.
=> T39420 Improve request parameter validation

api/models.py
This is to enable getting regression nodes matching attributes provided by query parameters.
- Implement `Node.translate_fields_with_operators` method to translate the parameter to `param={operator: value}
- Implement `Node.translate_timestamp_fields` method to translate ISOformat timestamp fields to `Date` object.
- Optimize `Node.translate_fields` to use above methods
- Implement `Regression.translate_fields`
=> T39493 Implement request query param translation for Regression model

api/main.py, api/models.py
This reverts commit b0fb415558a8668e037e753dbcca8a1787298790.
Drop the validation that a parent node needs to be in the "available" state for adding child nodes.  This is making things more complicated during development and it's not entirely clear yet whether this should be enforced in production either.
Also drop the call to validate_parent() from api.main.
=> Revert "api.models: implement `Node.validate_parent`"

.github/workflows/main.yml, api/models.py
Fixes https://github.com/kernelci/kernelci-api/issues/212
Add a job 'lint' using python-lint-annotate to run pylint with GitHub inline annotations.
Tested with https://github.com/kernelci/kernelci-api/pull/217
=> T40660 workflows: enable python-lint-annotate

.github/workflows/main.yml, docker/api/requirements-dev.txt, docker/api/requirements-tests.txt
Split `requirements-dev.txt` file into `requirements-tests.txt` and `requirements-linter.txt` files.
Add testing specific requirements to the `requirements-tests.txt` file.
Add linter specific requirements to `requirements-linter.txt`.
=> T40780 Split requirements from `requirements-dev.txt` file

README.md
Fix documentation related to running unit tests locally. Tweak `API Testing` section of `README.md`.
=> README.md: fix `API Testing` section

.github/workflows/test.yml, docker/test/Dockerfile, docker/test/requirements.txt, e2e_tests/conftest.py, e2e_tests/listen_handler.py, e2e_tests/test_count_handler.py, e2e_tests/test_node_handler.py, e2e_tests/test_pipeline.py, e2e_tests/test_pubsub_handler.py, e2e_tests/test_regression_handler.py, e2e_tests/test_root_handler.py, e2e_tests/test_subscribe_handler.py, e2e_tests/test_unsubscribe_handler.py, e2e_tests/test_user_creation.py, run_e2e_tests.sh, test-docker-compose.yaml
Fixes https://github.com/kernelci/kernelci-api/issues/199
Added `test-docker-compose.yaml` to introduce `test` service.
The service will run tests from `e2e_tests` package.
Added below tests:
- Test API root handler
- Test admin user creation and get access token
- Test regular user creation using admin bearer token
- Negative test for regular user creation
- Test for subscribe handler
- Test for unsubscribe handler
- Add a test pipeline for node handler with pubsub event listener
- Test for count handler
- Test for regression handler
Also, added `test.yaml` in github workflows to run tests within a test environment created by `test-docker-compose.yaml`.
=> T40027 Introduce end-to-end testing for API

README.md
Include instructions to run e2e tests locally for API in `API Testing` section.
=> T40027 README.md: add instructions for e2e tests

.github/workflows/main.yml, .pylintrc, api/models.py, docker/api/requirements.txt
Adjust how the URL fields are being defined in models to accept all types of Git URLs and validate that artifacts are a name -> HTTP URL mapping.
This required an upgrade of Pydantic, which in turn required some tweaks in the Pylint configuration.  I might split this into separate PRs if reviewing it is proving too difficult.
Among other things, this makes it possible to have a local Git repository rather than a remote one.  I've then been able to run a full pipeline without any Internet access*, and it speeds things up when iterating during development.  Here's what I changed in my local configuration:
In `pipeline.yaml`:
```yaml
trees:
local:
url: 'file:///home/kernelci/linux'
build_configs:
local:
tree: local
branch: 'master'
```
In `docker-compose.yaml`:
```yaml
tarball:
volumes:
- …
```
=> Adjust URL fields in models

tests/unit_tests/conftest.py, tests/unit_tests/test_count_handler.py, tests/unit_tests/test_listen_handler.py, tests/unit_tests/test_me_handler.py, tests/unit_tests/test_node_handler.py, tests/unit_tests/test_root_handler.py, tests/unit_tests/test_subscribe_handler.py, tests/unit_tests/test_token_handler.py, tests/unit_tests/test_unsubscribe_handler.py, tests/unit_tests/test_user_handler.py
Optimize unit tests.
Create base URL for FastAPI TestClient from default test server URL along with API version.
Instead of creating `TestClient` instance from unit test functions, use the fixture.
Drop using `API_VERSION` from the request paths as `TestClient.base_url` will contain it by default.
Also, drop imports for using API_VERSION and TestClient.
Created on top of https://github.com/kernelci/kernelci-api/pull/220
=> T41007 Optimize unit tests for API

api/main.py, tests/e2e_tests/test_user_creation.py, tests/unit_tests/test_whoami_handler.py
Rename the /me entry point as /whoami which refers to the standard "whoami" tool to retrieve information about the current user.  This is a better description of what the purpose of the endpoint and would avoid ambiguity with other endpoints related to the current user such as profile information etc.
=> api.main: rename "me" as "whoami"

README.md, doc/_index.md
Since the introduction of versioning, the generated documentation URLs need a prefix e.g. `latest`.  Update the README and static documentation accordingly.
=> Update generated API documentation URLs

docker/api/requirements.txt
Upgrade cloudevents to 1.9.0 to get the latest improvements and also enable checking type-safety with mypy.
=> docker/api: upgrade to cloudevents 1.9.0

api/pubsub.py
Fix the test that looks for user-provided attributes as it may be either None or an empty dictionary, not just None or valid attributes.
=> api.pubsub: fix attributes logic in publish_cloudevent

doc/api-details.md, doc/getting-started.md
Fixes https://github.com/kernelci/kernelci-api/issues/228
Since the implementation of versioned APIs, all the API endpoints have API version prefix i.e. `latest` for the current development version.
Fix all the URLs of sample curl commands with API version in `doc/getting-started` and `doc/api-details` pages.
=> T41423 Update documentation with `/latest` prefix in URLs

docker-compose.yaml, docker/storage/config/nginx.conf
Fixes https://github.com/kernelci/kernelci-api/issues/230 
Created directory `config`  under `docker.storage` to store configuration file for `storage` service.
Added `nginx.conf` file to modify `server` block copied from `/etc/nginx/conf.d/default.conf` to enable autoindex.
Mounted the config file in `docker-compose`.
=> T41424 Enable autoindex in nginx

create_admin_user
As a part of API versioning implementation, append API version `latest` suffix to default
URL used for requesting API endpoints to create an admin user. Adjust URL path for `/hash` endpoint accordingly for correct URL parsing.
=> T41382 Fix `create_admin_user` script with API version

doc/getting-started.md
Update the "getting started" documentation to refer to the renamed environment variable KCI_API_TOKEN to follow changes in the pipeline code.  This is to have a KCI_ prefix for all the KernelCI environment variables and avoid name clashes.
=> doc: update getting-started.md with KCI_API_TOKEN

README.md, doc/overview.md
Add the missing `latest/` API version prefix to URLs for the `openapi.json` file.  The URLs without the prefix return a top-level JSON file which is not a description of the actual API.
=> Fix URLs for `openapi.json`

api/db.py
Remove Database.find_all() method which is unused and in fact redundant as it's equivalent to .find_by_attributes() with no filter.
=> api.db: remove unused method .find_all()

api/db.py
The .find_one() collection method can use an ObjectId directly, which is simpler than providing a dictionary filter using '_id'.  Update all calls to .find_one() accordingly.
=> api.db: use ObjectId directly in .find_one()

api/models.py
Use (str, Enum) as mixin parent classes for Enum fields that are only strings.  This helps ensure that only strings are accepted as values for these Enum types.
=> api.models: use (str, Enum) as mixin for string enums

api/models.py
Remove const=True from Node.kind to allow it to have other values than the default 'node'.  This is to be able to deduce if Node.data should be validated against a particular model, or to know its type in general.
The original assumption was that we would have derivative classes from Node but this isn't too practical as the base class can't be used with Pydantic with derivated objects since it can't validate the extra fields.  So instead, Node can become a more general class rather than having specialised derivative ones.  The Node.data part can be used for specialisation instead.
=> api.models: allow Node.kind to take other values than 'node'

api/main.py, tests/e2e_tests/test_pipeline.py
Consolidate the code used to send events when Node objects are being created or updated, and add some extra fields to avoid always fetching the whole Node object.  This should provide enough information for a pipeline to determine which jobs should be run next based on the event itself.
=> Add extra fields in the Node event data

api/main.py, api/models.py
Drop the Node.validate_params() custom validation method used with GET queries as invalid values will not match any result and this is used with fuzzy-matching queries that don't validate the input using Pydantic.  Also, values of the wrong type are already reported as errors by the lower layers.  For example, with an invalid ObjectId:
$ ./kci node find parent=xyz --limit=1
400 Client Error: Bad Request for url: http://172.17.0.1:8001/latest/nodes?parent=xyz&limit=1
'xyz' is not a valid ObjectId, it must be a 12-byte input or a 24-character hex string
Other queries such as the POST and PUT ones rely directly on Pydantic to validate the input data against the model so there's no need for custom validation there either (and .validate_params() wasn't used in these cases, only with …
=> api.models: drop Node.validate_params()

api/models.py
Fix the below error while trying to get nodes with `kind=regression`:
```
today at 14:08:18INFO:     172.24.0.1:58850 - "GET /latest/nodes?kind=regression HTTP/1.0" 500 Internal Server Error
today at 14:08:18ERROR:    Exception in ASGI application
today at 14:08:18Traceback (most recent call last):
today at 14:08:18  File "/home/kernelci/.local/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 398, in run_asgi
today at 14:08:18    result = await app(self.scope, self.receive, self.send)
today at 14:08:18  File "/home/kernelci/.local/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
today at 14:08:18    return await self.app(scope, receive, send)
today at 14:08:18  File …
```
=> T41958 api/models: fix getting regression nodes failure

doc/api-details.md
A minor fixup in the curl command in the section to create API tokens with security scopes.
Fixes: ed759c8 ("doc: get API token with scope")
=> doc/api-details: fixup in sample command to create API tokens

api/db.py, api/main.py, api/models.py, init_user_groups, tests/e2e_tests/test_user_group_creation.py
Add support for user groups.
- Added model `UserGroup`
- Added a python script to create default groups i.e. admin and users
- Added POST handler for it
- Added GET handler for it
- Added e2e test for user group creation
=> Add support for user groups

api/main.py, api/models.py, create_admin_user, tests/e2e_tests/test_pipeline.py, tests/e2e_tests/test_subscribe_handler.py, tests/e2e_tests/test_user_creation.py, tests/unit_tests/conftest.py, tests/unit_tests/test_token_handler.py, tests/unit_tests/test_user_handler.py, tests/unit_tests/test_whoami_handler.py
Depends on https://github.com/kernelci/kernelci-api/pull/265
Introduced `user_group` field in `User` model. Updated API endpoint for creating users to receive user group from query parameter and use it for user model creation.
Added a migration file to set `user_group` value to `admin` for admin users and `users` for regular users.
Also, update the script for creating admin users to check the existence of `admin` group before creating admin users.
Updated e2e tests and unit tests for the related changes.
=> Store group in User model

tests/e2e_tests/test_pubsub_handler.py
Fixes https://github.com/kernelci/kernelci-api/issues/275
Test for pubsub uses pytest variable `test_channel_subscription_id` to listen to events on the test channel.
Since the subscription id variable is created from `test_subscribe_test_channel` test, insert a test dependency to the pubsub test handler.
This can avoid the below errors in case `test_subscribe_test_channel` fails,
```
kernelci-api-e2e-tests |         task_listen = create_listen_task(test_async_client,
kernelci-api-e2e-tests | >                                        pytest.test_channel_subscription_id)
kernelci-api-e2e-tests | E       AttributeError: module 'pytest' has no attribute 'test_channel_subscription_id'
kernelci-api-e2e-tests | 
kernelci-api-e2e-tests | e2e_tests/test_pubsub_handler.py:27: AttributeError
```
=> tests/e2e_tests: add a dependency to `test_pubsub_handler`

api/main.py, api/models.py, tests/e2e_tests/test_user_creation.py, tests/unit_tests/conftest.py, tests/unit_tests/test_token_handler.py, tests/unit_tests/test_user_handler.py, tests/unit_tests/test_whoami_handler.py
Created on top of https://github.com/kernelci/kernelci-api/pull/266
Fixes https://github.com/kernelci/kernelci-api/issues/278
`User.is_admin` field was introduced to verify if the user is an admin user. Now we have a specific user group `admin` and all the admin users will be assigned to it. Instead of `is_admin` flag, we can use `User.groups` to check if the user belongs to the `admin` group and hence we can check if it is an admin user.
Thus, we can drop `User.is_admin` field now.
=> Remove  `User.is_admin` field

api/main.py, tests/e2e_tests/test_user_creation.py, tests/unit_tests/test_whoami_handler.py
Use `response_model_by_alias` flag for `/whoami` endpoint to get response without alias. This is to fix `_id` field in the response.
=> api.main: fix response model to not have alias for `/whoami`

api/models.py
Fixes https://github.com/kernelci/kernelci-api/issues/283
To prevent duplicated user groups in `User.groups` list, use field type `conlist` from Pydantic.
=> api.models: apply unique items constraint to user groups

api/main.py
Fix `get_user_groups` to drop pagination parameters (i.e. limit and offset) from request query parameters.
Fixes: 7800343 ("api.main: add GET handler for user groups")
=> Fix `/groups` for pagination parameters

api/main.py, api/models.py, tests/e2e_tests/test_node_handler.py, tests/e2e_tests/test_regression_handler.py, tests/unit_tests/test_node_handler.py
Fixes https://github.com/kernelci/kernelci-api/issues/256
Add user ownership to nodes. 
- Add `Node.user_id` field to store user ID that created the node
- Added method to authorize user for PUT node requests
- Exclude `user_id` field from response data of node related requests i.e. GET, PUT, and POST
=> User ownership to nodes

docker-compose.yaml
Limit the MongoDB cache to 0.5 GB using the standard --wiredTigerCacheSizeGB command line argument.  The default value is to use 50% of the available RAM which is disproportionate for a regular development setup.
=> docker-compose.yaml: set MongoDB cache to 0.5 GB

api/admin.py, api/auth.py, api/db.py, api/main.py, api/models.py, tests/e2e_tests/test_user_creation.py, tests/unit_tests/conftest.py, tests/unit_tests/test_token_handler.py, tests/unit_tests/test_user_handler.py, tests/unit_tests/test_whoami_handler.py
Create a separate model to store user information that will be accessible publicly and can be updated by user. Store private information along with profile to `User` model and only admins will be allowed to access/update it.
=> Add user profile model

docker/api/requirements.txt
The version of PyYAML was not being specified and newer releases rely on more recent dependencies which cascade into basically updating FastAPI and some parts of the code accordingly.  While doing this would make sense to keep the API codebase up-to-date, pin down the PyYAML version to 5.3.1 for now in requirements.txt so we avoid the whole issue in the short term.
Fixes: https://github.com/kernelci/kernelci-api/issues/303
=> docker/api: pin PyYAML version to 5.3.1

api/main.py
Fixes https://github.com/kernelci/kernelci-api/issues/300
Implement an endpoint to get users.
It also accepts request query parameters to get matching user.
e.g. `http://API_URL/users?username=test`
=> api.main: GET users and user profiles

api/admin.py, api/auth.py, api/db.py, api/main.py, api/models.py, tests/e2e_tests/test_user_creation.py, tests/unit_tests/conftest.py, tests/unit_tests/test_token_handler.py, tests/unit_tests/test_user_handler.py, tests/unit_tests/test_whoami_handler.py
Depends on https://github.com/kernelci/kernelci-api/pull/292 for user profile changes.
api.main: set node ownership to a hierarchy of nodes
When submitting a hierarchy of nodes using `put_nodes`, set node ownership information to all the nodes recursively.
Also, use the `authorize_user` method for user authorization upon receiving the request.
=> Assign ownership details to a hierarchy of nodes

api/main.py
Remove `Optional` and make `Node.owner` a mandatory field. `Optional` was added as node ownership fields were not
present previously. Not marking the field `Optional` could have led to an issue for existing nodes on staging instance.
Update `authorize_user` method accordingly.
=> Update `Node.owner` to be a mandatory field

api/admin.py
Add an --admin-group command line argument to let the user override the admin group name which is "admin" by default.  The code base still implicitly depends on the magic "admin" group name for admin user permissions so in practice this shouldn't need to be used other than for development purposes right now.
=> api.admin: add --admin-group command line argument

doc/getting-started.md
Endpoint "/me" was replaced with "/whoami" in:
ef045973cf72cc70bda8736c73e8a62609275ad4
=> Update "Getting started" guide after setting up local environment

api/admin.py, api/main.py, api/models.py, tests/e2e_tests/test_user_creation.py, tests/unit_tests/conftest.py, tests/unit_tests/test_token_handler.py, tests/unit_tests/test_user_handler.py
Add `UserProfile.email` field to store user's email address. Update POST and PUT user handlers accordingly.
Also, update script to setup admin user to get admin email address.
=> Add email field to user profile

api/pubsub.py, test-docker-compose.yaml, tests/e2e_tests/test_pipeline.py, tests/e2e_tests/test_pubsub_handler.py
The keep-alive feature has now become necessary even for local docker-compose setups as the client code has a default timeout of 60s. Enable it with a default period of 45s to avoid this issue, which should also avoid hitting infrastructure errors which were the original reason for adding the keep-alive feature.
Fixes: https://github.com/kernelci/kernelci-pipeline/issues/290
=> api.pubsub: enable keep-alive with 45s default period

api/main.py, tests/e2e_tests/test_password_handler.py
This PR is an initial implementation of a feature requested as #298. It is still missing method in the `kernelci.api` base class, command for `kci user` as well as proper unit and e2e tests.
Fixes https://github.com/kernelci/kernelci-api/issues/298
=> Allow users to update their own password

doc/api-details.md
Fixes https://github.com/kernelci/kernelci-api/issues/322
Add instructions for adding variables for redis host and database URL configuration to `.env` file.
=> doc/api-details: environment variables for Redis and Database

tests/e2e_tests/test_subscribe_handler.py, tests/e2e_tests/test_user_creation.py, tests/e2e_tests/test_user_group_creation.py, tests/e2e_tests/test_user_group_handler.py
Fixes https://github.com/kernelci/kernelci-api/issues/289
Implement end-to-end tests for user group handlers.
It includes testing of POST and GET '/group' handlers.
=> e2e tests for user group handler

kube/minkube/api-deployment.yaml, kube/minkube/deployments/db-deployment.yaml, kube/minkube/deployments/redis-deployment.yaml, kube/minkube/deployments/ssh-deployment.yaml, kube/minkube/deployments/storage-deployment.yaml, kube/minkube/init/init-job.yaml, kube/minkube/init/init-pod.yaml, kube/minkube/pvc/db-pvc.yaml, kube/minkube/services/api-service.yaml, kube/minkube/services/db-service.yaml, kube/minkube/services/redis-service.yaml, kube/minkube/services/ssh-service.yaml, kube/minkube/services/storage-service.yaml
Fix the copyright statements for Sanskar Bhushan to follow the convention of listing the copyright owners directly rather than referring to the "authors".  In many cases, the authors don't own the copyright if they're writing the code as part of their work with an employer.
=> kube/minikube: fix Sanskar Bhushan copyright statements

pyproject.toml
Add an initial pyproject.toml file to be able to build and install the
api Python package.
Thanks to Nikolay Yurin for finding the bug about the license file:
https://github.com/pypa/pip/issues/12251
This project uses a standard license so it's better to just rely on
the LGPL-2.1-or-later SPDX indentifier instead of providing the path
to the whole license file.
Development dependencies have been omitted and all the required
dependencies have a fixed version in order to build reproducible
Docker images for production deployment.  Some follow-up changes can
be made to have a better way to handle dependencies for development.
=> pyproject.toml: add initial file

docker/api/Dockerfile.production
Add Dockerfile.production to build the kernelci/api Docker image for production deployment.  It installs the "api" package using pip directly in the image so it's self-contained.  This relies on pyproject.toml to be set up correctly.
This is an alternative to the standard Dockerfile used by docker-compose for a local deployment based directly on the source tree.
Depends on https://github.com/kernelci/kernelci-api/pull/328
=> docker/api: add Dockerfile.production

kube/aks/README.md, kube/aks/api.yaml, kube/aks/ingress.yaml, kube/aks/redis.yaml
Add the YAML files and README to create a deployment of the KernelCI API in AKS.
=> Add AKS deployment

doc/local-instance.md
Rename the getting-started page to local-instance as it's more about setting up a local instance with docker-compose than starting to use the API from a user point of view.  Update the Hugo front-matter accordingly.
=> doc: rename getting-started to local-instance

doc/api-details.md, doc/local-instance.md
Fixes https://github.com/kernelci/kernelci-api/issues/313
`User` model schema has been changed to have user profile fields. Also, the script for creating admin users has been changed accordingly. Update the documentation in `local-instance` and `api-details` pages.
=> Update documentation for creating user accounts

api/main.py, tests/e2e_tests/test_pipeline.py
Fixes https://github.com/kernelci/kernelci-api/issues/343
In order to enable filtering nodes based on owner, add node owner information to pubsub event data for `node` channel.
=> api.main: add node owner information to pubsub event

doc/early-access.md
This patch fixes minor typos in the provided configuration examples.
=> doc/early-access: fix API token configuration examples

kube/aks/README.md
Fix a typo in `Set up the ingress` section.
=> kube/aks/README.md: fix a minor typo

api/admin.py
Fixes https://github.com/kernelci/kernelci-api/issues/335
Add a retype password prompt while creating admin user using `admin.py` script to avoid typos.
=> api.admin: add password confirmation prompt

kube/minikube/scripts/setup_admin_user.sh
Added a script `kube/minikube/scripts/setup_admin_user.sh` to setup an admin user for k8s API instance.
At first, the script will get the pod name of `kernelci-api` service running on Minikube. Then it will run `api.admin` module inside the pod container to create an admin user.
=> k8s: script to setup admin user

api/db.py, api/models.py
Not equal is one of necessary basic mongodb operators, which might come handy to exclude certain results.
=> api.operators: Add ne operator

api/main.py
If we submit over kci tool node with non-existing ID, then we will get exception:
```
[api-77fd989c9c-mdzjr]: INFO:     10.244.1.36:55856 - "PUT /latest/node/aaaabbcf8326c545a780f36c HTTP/1.1" 500 Internal Server Error
[api-77fd989c9c-mdzjr]: ERROR:    Exception in ASGI application
[api-77fd989c9c-mdzjr]: Traceback (most recent call last):
...
[api-77fd989c9c-mdzjr]:   File "/home/kernelci/.local/lib/python3.10/site-packages/fastapi/dependencies/utils.py", line 550, in solve_dependencies
[api-77fd989c9c-mdzjr]:     solved = await call(**sub_values)
[api-77fd989c9c-mdzjr]:   File "/home/kernelci/.local/lib/python3.10/site-packages/api/main.py", line 130, in authorize_user
[api-77fd989c9c-mdzjr]:     if not user.profile.username == node_from_id.owner:
[api-77fd989c9c-mdzjr]: AttributeError: …
```
=> api/main.py: Fix exception when node doesn't exist

doc/early-access.md
Clarify the documentation about setting up storage to also mention that it's convenient to add storage_config to the settings file to avoid having to keep passing --storage-config on the command line.
=> doc/early-access: clarify staging_config settings

doc/_index.md
Remove the link to the definition of a DAG as the nodes form a simple tree structure which isn't really a DAG.  Nodes don't have multiple parents.
Fixes: b3113449fe78 ("doc: rewrite overview with more information")
=> doc: remove DAG reference as it's just a plain tree

doc/_index.md, doc/api-details.md, doc/pipeline-details.md
Remove leftover bits at the bottom of the API overview page and adjust things accordingly.
=> Fix some loose ends in the API overview page

doc/api-details.md
Fix the link to the part about creating admin users as this should be an absolute URI with a leading / rather than a relative one.
Fixes: c752060d7683 ("doc/api-details: update `user` section")
=> doc: fix absolute link for creating admin users

api/main.py
Update handler name for PUT `/user/profile/<username>` endpoint.
Add proper docstring for the handler.
Also, make `email` field optional in the request query parameter in case user does not want to update it.
=> api.main: PUT '/user/profile' endpoint improvments

tests/unit_tests/conftest.py, tests/unit_tests/test_count_handler.py, tests/unit_tests/test_listen_handler.py, tests/unit_tests/test_node_handler.py, tests/unit_tests/test_root_handler.py, tests/unit_tests/test_subscribe_handler.py, tests/unit_tests/test_token_handler.py, tests/unit_tests/test_unsubscribe_handler.py, tests/unit_tests/test_user_group_handler.py, tests/unit_tests/test_user_handler.py, tests/unit_tests/test_whoami_handler.py
Pytest fixture `mock_init_sub_id` is used to mock Pub/Sub initializer function call. As the function is called on app startup, all the unit tests call it by default upon test execution. Instead of explicitly calling the fixture from all the tests, mark the fixture with `autouse=True`. This will make all tests automatically request it.
=> tests/unit_tests: autouse `mock_init_sub_id` fixture

README.md
Test directory structure has been changed
to have two separate directories for unit tests and e2e tests named `unit_tests` and `e2e_tests` respectively. Fix command to run unit tests in the README.md file by renaming test directory.
=> README.md: fix `API Testing` section for unit tests

tests/unit_tests/test_listen_handler.py
Eliminate request to mock function for Pub/Sub initialization from `/listen` handler tests.
Fixes of what I missed in https://github.com/kernelci/kernelci-api/pull/382
=> tests/unit_tests: remove request to init Pub/Sub mock

api/main.py
Fixes https://github.com/kernelci/kernelci-api/issues/337
Instead of returning HTTP 404 error when request URL has no version number prefix, redirect the request with '/latest' version.
e.g. when user tries to access `http://localhost:8001`, redirect it to `http://localhost:8001/latest`.
The middleware will check the version from the request path with available API versions using `API_VERSIONS` tuple.
=> api.main: add middleware for HTTP requests

api/main.py
Return HTTP 400 when trying to use a version that doesn't exist e.g. `http://host/v1/`
Follow-up from #367
=> HTTP redirect error handling

doc/early-access.md
Update the Early Access setup documentation page with the reworked kci command line syntax and related TOML settings.
Fixes https://github.com/kernelci/kernelci-core/issues/2158
=> doc: update Early Access page with latest kci

doc/early-access.md
The config settings (--yaml-config) can take several values, but the first one should be the standard one in /etc/kernelci/core when adding a custom file on top of it.  Fix this instead of relying on a local config/core copy of the files.
Fixes: e8e94267a669 ("doc: update Early Access page with latest kci")
=> doc: fix multiple config paths setting on Early Access page

doc/early-access.md
The Azure File name might not be exactly the same as the username so add a note about that.  Also add a related note about putting values in double quotes when they contain a dot so it gets parsed correctly in TOML with the dotted-key syntax.
=> doc: add notes about Azure File share names

api/admin.py
Bypass the email verification step when creating the first superuser as this is a special case.  Administrators should be able to create this entry entirely non-interactively, and they should also have direct access to the database anyway where this flag could be set by hand.
=> api.admin: set is_verified=1 for the first superuser

api/user_manager.py
Show the username in log messages in addition to the user ID.  This makes it much easier to follow the logs when checking user activity.
=> api.user_manager: add username in log messages

api/auth.py, api/config.py, api/email_sender.py, api/pubsub.py, api/user_manager.py
Instead of defining multiple settings class in different API modules like `pubsub`, `auth`, `email_sender`, add `api.config` module to store all different settings classes.
Replaces #392
=> api.config: add module to define various settings (was #392)

api/main.py, api/user_manager.py
This PR fixes several issues found when testing the new user management implementation:
* `api.user_manager: call UserManager parent with all arguments`
This is to avoid unexpected behaviour and fix hidden bugs.
* `api.main: rely on create_user_manager()`
This is to have only one way of creating the UserManager objects and simplify the code
* `api.user_manager: create EmailSender only when required`
This is to avoid requiring SMTP settings unless when actually trying to send an email
* `api.main: only look for duplicate user when required`
This is to remove unwanted checks for duplicate users when no new username is being provided
=> Fix several issues related to user management

api/main.py
Fix `_set_node_ownership_recursively` method to use `User.username` to get username as per the latest `User` schema while setting node ownership.
=> api.admin: fix method for setting node ownership

api/admin.py, api/user_models.py
Since `profile` field has been eliminated from `User` schema, update logic to check existing admin user by matching `username` field.
Fixes #401
=> api.admin: fix `setup_admin_user`

api/main.py
HTTP middleware is not redirecting requests when received with no version prefix. Fix it by using versioned API instance instead of `FastAPI` instance.
Fixes: 8e23ec5 ("api.main: rename versioned app instance")
=> api.main: fix HTTP middleware

api/db.py, api/main.py
implement DELETE `/group/<group-id>` endpoint to delete a user group.
Remove users from that group before deleting it. Also, check if the group is assigned to any node and remove it from user groups that are permitted to update the node.
=> Implement endpoint to delete a user group

api/main.py, api/pubsub.py, docker/api/requirements-tests.txt, docker/api/requirements.txt, tests/unit_tests/test_pubsub.py
Use Redis list for enabling support for unicast messages for load-balancing use-case.
Introduced endpoints `/push` and `/pop` for pushing messages to a Redis list and popping a message from the
list respectively.
=> Enable support for unicast messages

api/main.py
Only allow authorized users to get user details matching given user ID to protect user's personal information.
=> api.main: perform authorization for GET '/user/<id>'

api/main.py, api/models.py, api/pubsub.py, tests/e2e_tests/test_subscribe_handler.py, tests/unit_tests/conftest.py, tests/unit_tests/test_pubsub.py, tests/unit_tests/test_subscribe_handler.py
This PR features a first basic step towards proper event filtering and handling. User ownership data is added to events and subscriptions, and the ownership is checked by default in "listen" and "unsubscribe" operations.
The `Subscription` model now includes a `user` field to store the username associated to the subscription (ie. the "owner"). **NOTE: This assumes that usernames are unique.**
The `PublishEvent` model was simplified and the processing of events through the `publish` endpoint now includes an implicit definition of the event owner and it allows overriding the default "type" and "source" attributes (if that's ever needed, if not we can remove this) and adding other extra attributes freely. From a users perspective, the only mandatory field in the request is `data` (dict). Any …
=> Implement event ownership

api/email_sender.py
Add `try-catch` block to `EmailSender._send_email` method to catch exception while sending emails.
=> api.email_sender: catch SMTP related exceptions

api/pubsub.py
Shut down `PubSub` connection in `unsubscribe` method for proper cleanup.
=> api.pubsub: shutdown pubsub connection

api/admin.py, api/main.py, tests/e2e_tests/test_pipeline.py, tests/e2e_tests/test_subscribe_handler.py, tests/e2e_tests/test_user_creation.py, tests/e2e_tests/test_user_group_handler.py, tests/unit_tests/conftest.py, tests/unit_tests/test_user_handler.py
With `fastapi-users` integration, `User.is_superuser` flag has been introduced to identify admin users. 
This eliminates the requirement for creating any specific user group for admin users. Hence, discard the method to setup `admin` user group from the script.
=> Remove `admin` user group

kube/minikube/api-deployment.yaml, kube/minikube/configmap/api-configmap.yaml
Define `ConfigMap` variables for email-related configurations. Update `api` deployment file to use newly added configurations.
=> kube/minikube: add email configuration variables

api/admin.py
Fixes https://github.com/kernelci/kernelci-api/issues/444
Created on top of https://github.com/kernelci/kernelci-api/pull/436
Staging has multiple users with the same email address. Fix the bug in admin user setup script.
=> Bug fix: admin users with duplicate email

api/db.py, api/main.py, migrations/20231215122000_node_models.py, tests/e2e_tests/test_pipeline.py, tests/e2e_tests/test_regression_handler.py, tests/unit_tests/test_node_handler.py
**NOTE**: These changes _will_ break an API instance that is connected to a DB with existing nodes, since this changes the node models. The [db migration script](https://github.com/kernelci/kernelci-api/pull/395/commits/8792522463799f95554b793eb4f36bdeb3399b77) included in the changes handles the data migration cleanly (hopefully).
Related PRs:
- https://github.com/kernelci/kernelci-pipeline/pull/365
- https://github.com/kernelci/kernelci-core/pull/2224
https://github.com/kernelci/kernelci-core/pull/2224 and this PR are interdependent, so they should be merged together. I suggest https://github.com/kernelci/kernelci-core/pull/2224 is merged first, then this one and then https://github.com/kernelci/kernelci-pipeline/pull/365. Remember to apply the migration scripts.
This PR has already …
=> Rework models

run_e2e_tests.sh, test-docker-compose.yaml, tests/e2e_tests/test_pipeline.py
- Fix pipeline test (sync it to Node model changes)
- The "test" service of test-docker-compose.yaml no longer launches the tests on startup. Update the run_e2e_tests.sh script to start the service and run the tests.
- Fix inconsistencies in pytest dependencies
=> Assorted e2e test updates

doc/api-details.md
As the `Getting started` page has been renamed to `Local instance`, update the link to the section for creating environment variables.
Fixes: eefbece ("doc: rename getting-started to local-instance")
=> doc/api-details: fix reference to `Getting started` page

api/db.py
Introduce a new API query operator (re) to match query parameters using mongodb-compatible regular expressions.
Mongodb has built-in regex capabilities for queries, so we get those for free if we simply add support for an additional query operator.
=> api.db: add support for regexes in mongodb queries

doc/early-access.md
Tool "kci" expects email as an argument (not the user name):
```
$ ./kci user verify --help
Usage: kci user verify [OPTIONS] EMAIL
(snip)
```
=> doc/early-access: use correct argument for email verification

doc/api-details.md
Sync the docs to the current model definitions and mention the `__re` operator, including an example.
=> doc/api-details: update Node examples, model format and operators

pyproject.toml
Fixes https://github.com/kernelci/kernelci-api/issues/469
New python packages were added to `requirements.txt` after `fastapi-users` integration.
Add all those packages to `pyproject.toml`. Also, re-order the existing packages to maintain package version dependencies.
Added a section for optional dependencies as well. The package can be installed with the below commands
including optional dependencies:
To run API tests: `python3 -m pip install .[tests]` 
For developer mode: `python3 -m pip install .[dev]`
=> pyproject.toml: add missing modules to project deps

pyproject.toml
Only the `api` directory is included with the python package atm. Add directories such as templates and scripts to run API container properly to the package.
=> pyproject.toml: add package directories such as templates and scripts

api/main.py, templates/viewer.html
This is PoC of API viewer for development purposes.
=> viewer: Add HTML helper to view nodes

test-docker-compose.yaml
Use docker image for building api container for running tests.
=> test-docker-compose: use `kernelci/staging-api` image

api/db.py, api/models.py
Depends on https://github.com/kernelci/kernelci-core/pull/2399
Closes https://github.com/kernelci/kernelci-api/issues/437
Implement a dataclass `Index` to store model field names and constraints to create indexes. Instead of directly creating indexes from model method for specific DB engine (at the moment, MongoDB), implement a method to get indexes from models independent of DB engine i.e. list of
`DatabaseModel.Index` class instances. Create MongoDB specific indexes in the database method `Database.create_indexes`.
=> api.db: decouple model indexes from DB engine

scripts/run_e2e_tests.sh, test-docker-compose.yaml
All the scripts are stored in the `scripts` directory.     Move `run_e2e_tests.sh` script to that directory as well.
Also, update the command running e2e tests to use `tests/e2e_tests` as `tests` container has mounted volume
`tests/`.
=> Move e2e tests script to `scripts/` directory

scripts/run_unit_tests.sh
Add `scripts/run_unit_tests.sh` for running API unit tests.
=> scripts: add script to run API unit tests

scripts/run_e2e_tests.sh
Created on top of https://github.com/kernelci/kernelci-api/pull/490
scripts/run_e2e_tests: add build argument
Add `no-cache` build argument while building images for tests.
=> Add build argument for `e2e` tests

docker-compose.yaml
Instead of doing local build - use docker image from registry.
=> docker-compose.yaml: Update API to use docker image

test-docker-compose.yaml
Depends on https://github.com/kernelci/kernelci-core/pull/2415
Use `kernelci/staging-api` image for creating tests container.
=> test-docker-compose: use docker image for `tests` container

tests/e2e_tests/test_count_handler.py, tests/e2e_tests/test_password_handler.py, tests/e2e_tests/test_pipeline.py, tests/e2e_tests/test_pubsub_handler.py, tests/e2e_tests/test_regression_handler.py, tests/e2e_tests/test_subscribe_handler.py, tests/e2e_tests/test_unsubscribe_handler.py, tests/e2e_tests/test_user_creation.py, tests/e2e_tests/test_user_group_handler.py
Related to https://github.com/kernelci/kernelci-api/pull/490
Docker container for running tests uses `tests` volume instead of `tests/e2e_tests` now. Update all the test dependency markers to use test file path starting from `tests/` accordingly.
=> tests/e2e_tests: fix dependency markers

.github/workflows/main.yml
Add `--no-cache` build argument in the `main` workflow to fetch latest docker image every time while building docker containers.
=> workflows/main: add `--no-cache` build argument

api/main.py
Fix the below pylint error:
```
api/main.py:741:4: W0621: Redefining name 'root' from outer scope (line 112) (redefined-outer-name)
```
=> api.main: fix `pylint` error

dev-docker-compose.yaml, docker/api/Dockerfile
Enable developer to use local volume binds by adding `dev-docker-compose.yaml` file. Also, add `Dockerfile` to provide the ability to build `api` container locally. This file is intended for developer use only.
=> Add `docker-compose` file for developer mode

.github/workflows/main.yml, .github/workflows/test.yml, api/main.py, docker/api/Dockerfile, docker/api/requirements-dev.txt, docker/api/requirements.txt, pyproject.toml, tests/e2e_tests/conftest.py, tests/e2e_tests/test_count_handler.py, tests/e2e_tests/test_root_handler.py, tests/e2e_tests/test_subscribe_handler.py, tests/e2e_tests/test_unsubscribe_handler.py, tests/e2e_tests/test_user_creation.py, tests/unit_tests/conftest.py
Fixes https://github.com/kernelci/kernelci-api/issues/479
Upgrade Python version to 3.11 for API. Update docker recipe that is being used for Developer mode to use `Python 3.11` image.
Update requirements version to enable support for Python 3.11.
Below are the required changes:
- `httptools` that is a requirement for `uvicorn`, failed to
build for existing package version that was `0.13.4`.
```
gcc -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I/usr/local/include/python3.11 -I/tmp/pip-install-o_24u7rm/httptools_8955220ea3f34d0bae14ed2b27b468ae/vendor/http-parser -c httptools/parser/parser.c -o build/temp.linux-x86_64-cpython-311/httptools/parser/parser.o -O2
httptools/parser/parser.c:212:12: fatal error: longintrepr.h: No such file or directory
212 |   #include "longintrepr.h"
| …
```
=> T40464 Upgrade API to python 3.11

docker-compose.yaml
We need to increase a bit staging ram, as dataset keep growing.
=> docker-compose.yaml: Ramp up staging mongo RAM

docker-compose.yaml, test-docker-compose.yaml
Depends on https://github.com/kernelci/kernelci-core/pull/2485
Template for building `api` docker image has been updated to use `kernelci` fragment for using `kernelci` python package.
Hence, use `kernelci` tag for `kernelci/staging-api` image.
=> Use `kernelci` tag for `kernelci/staging-api` image

api/config.py
To have at least some token variability we need to add more entropy. Setting expiration to 10 years might be enough, as it will force token signed data to include this information.
=> api/config: Add token expiration

doc/_index.md
The temporary Atlas account which was created for Early Access is now being closed, and as a result the link to the dashboard will stop working.  Remove the paragraph with the embedded Atlas dashboard graph showing the number of nodes.
=> doc: remove paragraph with Atlas graph

doc/api-details.md, doc/local-instance.md
Fixes: https://github.com/kernelci/kernelci-api/issues/422
As per the current user management scheme, there is no constraint for admin users to be a part of `admin` user group.
Only `is_superuser=true` flag is required while creating admin users. 
Update documentation accordingly.
=> doc: tweak `admin` user creation doc

doc/developer-documentation.md, doc/local-instance.md
Fixes https://github.com/kernelci/kernelci-pipeline/issues/574
Add a manual for enabling new kernel tree in the newly added page for Developer documentation.
=> doc: add "Developer documentation" page

api/main.py, tests/e2e_tests/test_pipeline.py
Add a boolean key named `is_hierarchy` node event data that denotes if the node event represents submission of node hierarchy. It would be required to distinguish such events from single node create/update events.
=> api.main: add `is_hierarchy` to node event data

api/main.py
Fixes https://github.com/kernelci/kernelci-api/issues/534
Fix the below validation error while requesting user password update:
```
{"detail":"1 validation error for UserRead\nresponse\n  none is not an
allowed value (type=type_error.none.not_allowed)"}
```
The endpoint returns null on successful request even if response model is specified (and it's not None).
=> api.main: fix POST `/user/update_password` endpoint

api/main.py, api/models.py, api/pubsub.py, tests/e2e_tests/test_subscribe_handler.py, tests/unit_tests/test_subscribe_handler.py
Some labs need to subscribe to all events, so they can receive other users kernel builds. Implement optional "promiscuous" option to make subscription listen to all users events.
=> api: Implement pub/sub promisc mode

README.md, pyproject.toml
Documentation has been migrated to the "docs.*" subdomain.
=> Fix links after docs page migration

api/templates/viewer.html
Since the "LAVA Job" button was first implemented, a few LAVA labs have been connected to KernelCI. Using the "LAVA Job" button for jobs scheduled on those would then error out, the base URL being `undefined`.
Add the missing labs so we can more easily inspect LAVA logs and job definitions.
=> api: templates: viewer: add missing LAVA URLs

api/main.py
Remove the hack of setting `node.submitter` field. The pipeline service and `kci_maintainer` tool should set the field instead while submitting node.
=> api.main: remove default `node.submitter`

api/db.py
If parent is set to same id as object it might cause loops in some of pipeline programs. Block such updates.
=> fix(db): Do not allow creating objects with wrong parent

pyproject.toml
Closes https://github.com/kernelci/kernelci-api/issues/513
Include migration script with `kernelci-api` python package for developer requirements.
=> pyproject.toml: include `migration` script to package

api/db.py
Add event history collection for new api endpoint
=> feat(db/models): Add eventhistory collection

api/db.py, api/main.py
This is non-paginated version of get_nodes query,
to test if it solves performance/latency issues.
=> feat(main.py): Non-paginated get_nodes 

api/db.py, api/main.py
For storing pipeline settings and variable and make them a bit more stateful we need reliable key/value store.
=> feat(api): Add key/value store with namespace emulation

api/main.py, api/metrics.py
Move `Metrics` class implementation to separate file to reduce number of lines in `api.main` module and to keep the various modules more organized.
Otherwise pylint will complain with the below error: "api/main.py: C0302: Too many lines in module (1044/1000) (too-many-lines)"
=> api: add `metrics.py`

api/main.py
Fixes https://github.com/kernelci/kernelci-api/issues/563
Depends on https://github.com/kernelci/kernelci-core/pull/2738
On update node operation, node ownership fields shouldn't be changed such as `owner` and `submitter`.
=> api.main: do not reset node ownership fields

api/main.py
Fixes https://github.com/kernelci/kernelci-api/issues/427
Fix `DELETE /group/{group-id}` endpoint's response model by using `pagination_ctx`.
=> api.main: fix delete user group endpoint

api/models.py
Remove model serializers of `User` and `UserRead` classes as model serializer of the parent class `DatabaseModel` handles its serialization in `json` mode.
=> api.models: remove user model serializers

doc/api-details.md
Closes https://github.com/kernelci/kernelci-api/issues/502
Describe API support for querying the same field with multiple operators e.g. date range queries.
=> doc/api-details: document date range queries

api/db.py
Fixes https://github.com/kernelci/kernelci-api/issues/575
Database `update` method was breaking while creating a `User` model with `is_superuser=1` field value.
Fix the method by separating `Node` specific logic from other model updates based on below facts:
- `obj.update()` will trigger `BeanieBaseUser.update()` for `User` model and not `DatabaseModel.update()`
- `User` model doesn't have `parent` field
=> api.db: fix `Database.update` method

doc/api-details.md
Closes https://github.com/kernelci/kernelci-api/issues/521
Document user and user group endpoints.
=> User management endpoint documentation

api/main.py, api/models.py
Related to https://github.com/kernelci/kernelci-api/issues/560
Fix the below warnings from pydantic v2 while creating or updating a user account with user groups:
```
kernelci-api          | /home/kernelci/.local/lib/python3.11/site-packages/pydantic/main.py:390: UserWarning: Pydantic serializer warnings:
kernelci-api          |   Expected `str` but got `UserGroup` with value `UserGroup(id=ObjectId('64...16ad'), name='kernelci')` - serialized value may not be as expected
kernelci-api          |   return self.__pydantic_serializer__.to_python(
```
Fix the issue by defining and using different user models for API endpoint and fastapi-users router, i.e. different
models as request schema for API request model and schema for request to `fastapi-users` router.
For create user request, user …
=> Fix pydantic v2 warnings related to `UserGroup`

api/main.py
If node updated, this means it is node with new data, that needs to be reprocessed by kcidb again, thus we need to reset flag!
=> fix(main.py): Reset kcidb flags on node update

api/main.py
If user abuse db query, it should not block HTTP server for long time.
=> fix(main.py): Introduce request time limit on fast requests

api/main.py
Implement batch "field to value" bulk set to improve speed of some batch operations.
This way we can update field on multiple nodes to particular value at once.
=> feat(main.py): Implement /nodes/set endpoint

api/main.py
Do not fail if one of nodes have wrong ownership, just ignore this node.
=> fix(main.py): Improve bulk-set robustness

api/main.py
If state changed, likely we need to reprocess the node.
Also make pylint a bit happier.
=> fix(main.py): Reset kcidb flag on state change

api/main.py, scripts/setup_admin_user
Newer version of docker-compose is called as "docker compose", so try automatically to use it, if docker-compose is missing.
=> fix(setup_admin_user): Script should be flexible on docker-compose

.github/workflows/test.yml, kube/aks/api.yaml, kube/aks/mongo.yaml, kube/aks/redis.yaml
Manifest is missing, while it is very important for service.
Also upgrade disk allocation to 15Gb
=> fix(k8s/mongo.yaml): Fix missing mongodb manifest and other k8s fixes

kube/aks/mongo.yaml
On some operations seems mongo create temp files
which easily exceed available disk space.
=> fix(k8s): Update disk allocation

kube/aks/ingress.yaml
We released new nice domain from legacy, so let's activate it in k8s, and use as main endpoint for Maestro API.
=> (k8s): Add api.kernelci.org domain to api ingress

doc/staging.md
Explain a bit better way how staging instance works, also remove encouragement to obtain Staging credentials, because it is needed only in very specific cases.
=> (docs) Update staging documentation

doc/staging.md
First sentence of the adjusted section already mentions ability to test the latest changes and features before they are merged into the production KernelCI API.
=> docs: Avoid repetition

.github/workflows/main.yml, api/main.py
Superusers can update others nodes, for example needed if kcidb bridge are processing other user nodes.
This is temporary hack to make sure qualcomm setup works.
=> (main.py) Make KernelCI system users as superusers

api/main.py
Even though the `data.result` query parameter can be added when calling the `/events` endpoint, add the `result` parameter for convenience.
This will also shorten the entire query and hide some of the internal implementation details from the end-user, as in the future, the query parameters might be sanitised such that any unknown or unsupported values could be removed.
=> Add query parameter to events endpoint to filter on result

api/main.py
Make superusers production and staging.kernelci.org in one more place.
=> (main.py) Add workaround for qualcomm

kube/aks/ingress.yaml, kube/aks/mongo.yaml
In case of mistake, if pv/pvc deleted better to change policy to Retain, so we can recover the data.
=> (k8s) Change policy on mongodb volume to Retain

api/main.py, api/maintenance.py
We need to be more flexible, to accept bigger batch size for cleanup, and also to return information, when cleanup is done.
=> api/maintenance: Return information about cleaned up nodes and accept batch size

api/main.py, api/templates/stats.html
This page will help to show approximate rate of infrastructure failures.
=> templates: statistics page to monitor infrastructure error rate

api/templates/stats.html
Turned out, on production we have almost 1000 builds per week, so default is not enough. Let's make few options more.
=> template/stats: Make limit configurable

tests/unit_tests/test_node_handler.py
Changes (https://github.com/kernelci/kernelci-core/pull/2746 and https://github.com/kernelci/kernelci-core/pull/2927) to the model caused unit tests to get out-of-sync with its new state.
Tests adjusted in this patch should be kept in sync with [Node class from "kernelci/api/models.py" in "kernelci/kernelci-core" repo](https://github.com/kernelci/kernelci-core/blob/ee64d7e4cdaeef2176d9755c9112ff97c8ad8e3a/kernelci/api/models.py#L184)
=> tests/unit_tests: sync unit tests after model changes

kube/aks/mongo.yaml
As we are reaching capacity, it is better to add more space, as during some operations we might exceed free space.
=> k8s: Increase disk size
