kernelci/kernelci-api

- .github/workflows/main.yml
Add .github/workflows/main.yaml with a check to run `pycodestyle` in the `api` directory.
> github: add main workflow with pycodestyle

- api/auth.py
- api/db.py
- api/main.py
- docker/api/requirements.txt
close #1 
add motor to requirements
update api.db to use motor
use async in api.main where it's missing
drop pymongo from requirements.txt
> [Close #1] Use motor instead of pymongo

- api/client.py
api/client.py : Fix Unprocessable Entity Exception for listen
Provided subscription ID instead of channel name
> pub/sub events issue : listen

- api/main.py
- api/pubsub.py
api/client.py: Fix Unprocessable Entity Exception for listen
api/pubsub.py: Fix cloudevents MissingRequiredFields exception for publish
> Fix pub/sub events : publish

- README.md
> README.md: Renamed shell script used for testing env setup

- api/main.py
> api/main.py: Fix undefined 'channel' variable in listen endpoint

- api/test_api.py
Fixes https://github.com/kernelci/kernelci-api/issues/46
api/test_api.py: Add test case for /me endpoint
> API unit test case for /me endpoint

- README.md
- docker/docker-compose.yaml
- docker/ssh/Dockerfile
- docker/ssh/sshd_config
Fixes https://github.com/kernelci/kernelci-api/issues/16
docker/ssh/Dockerfile: Add command to copy sshd_config file
docker/docker-compose.yaml: Add ssh section
docker/ssh: Add authorized_keys.sample file
README.md: Add 'Generate SSH key' section
> Add SSH container

- .github/workflows/main.yml
- api/auth.py
Fix all Pylint errors in api.auth and enable it in GitHub checks.
> api.auth: fix all Pylint errors

- api/db.py
- api/main.py
- api/models.py
api/main.py: Remove 'Thing' associated endpoints
api/models.py: Remove 'Thing' model
api/db.py: Remove 'Thing' from Database.COLLECTIONS
> Remove 'Thing' model and associated endpoints

- api/main.py
Fixes: https://github.com/kernelci/kernelci-api/issues/66
api/main.py: Add put_node handler
api/main.py: Remove the logic to update Node from post_handler()
> Implement HTTP PUT to update Node object

- .github/workflows/main.yml
- api/db.py
Fix all pylint errors in `api.db` module and run it in GitHub actions.
> Fix pylint errors in api.db and run it in GitHub actions

- .github/workflows/main.yml
- api/pubsub.py
Fix Pylint warnings in api.pubsub and run it in GitHub Actions
> Pylint api.pubsub

- .github/workflows/main.yml
- test/conftest.py
- test/test_listen_handler.py
- test/test_me_handler.py
- test/test_node_handler.py
- test/test_pubsub.py
- test/test_root_handler.py
- test/test_subscribe_handler.py
- test/test_token_handler.py
- test/test_unsubscribe_handler.py
test: fix pylint errors
github: enable pylint to run on test files
> Fix pylint errors in test and run it in GitHub actions 

- .github/workflows/main.yml
- test/conftest.py
- test/test_listen_handler.py
- test/test_me_handler.py
- test/test_node_handler.py
- test/test_subscribe_handler.py
- test/test_unsubscribe_handler.py
Fixes https://github.com/kernelci/kernelci-api/issues/113
Created on top of https://github.com/kernelci/kernelci-api/pull/112
> Fix pylint duplicate code error

- test/conftest.py
- test/test_pubsub.py
Include a test to validate if the json is generated and its attributes are correct.
Signed-off-by: Alexandra Pereira <alexandra.pereira@collabora.com>
> test/test_pubsub.py: test publish_cloudevent json

- api/pubsub.py
Send events periodically on all active channels to keep TCP
connections alive.  This is to avoid proxies and firewall closing them
due to inactivity.
> api.pubsub: add keep-alive periodic events

- api/main.py
Fixes https://github.com/kernelci/kernelci-api/issues/118
Add 'get_root_node/' endpoint to get root node
by providing node id to it.
It uses Node.parent attribute to fetch root node.
> api/main.py: implement endpoint to get root node

- doc/getting-started.md
Add a documentation section about how to get started with a local instance.
Depends on #126
> T33705 doc: add getting-started

- README.md
- api/db.py
- api/models.py
- test/test_node_handler.py
Fixes https://github.com/kernelci/kernelci-api/issues/38
Depends on #109
> Add 'updated' field to Node model

- README.md
Add links to https://kernelci.org/docs for the instructions
and remove duplicate information from the file.
> README.md: Use documentation from kernelci.org/docs

- api/main.py
- api/models.py
api/main.py: Add status and parent parameters to get_nodes
api/models.py: Add Node.modify_query_params
> Fix get node by attributes endpoint for parent attribute

- api/main.py
- api/models.py
api/models.py: add 'validate_params' method
api/main.py: validate params in '/nodes' endpoint
> T35091 Add method to validate request parameters

- api/auth.py
- api/main.py
- api/models.py
- api/pubsub.py
> T35229 Add field definitions to data model

- .github/workflows/main.yml
- api/main.py
api/main.py: fix pylint errors
api/main.py: update copyright header
github: enable pylint on api.main
> T35143 Enable pylint on  api.main

- api/main.py
Depends on https://github.com/kernelci/kernelci-api/pull/141
Develop an endpoint to create user with a
POST request.
> T35275 api/main.py: implement /user endpoint

- doc/overview.md
Signed-off-by: Alexandra Pereira <alexandra.pereira@collabora.com>
> kernelci-api/doc: update test report description

- api/models.py
- doc/api-details.md
- test/test_node_handler.py
Need to update Node model to accommodate status and result separately.
Update unit tests and documentation for the same.
> T36372 Update Node model with status and result

- api/db.py
- api/main.py
- api/models.py
Implement models and endpoints for regression tracking.
> T35922 Regression tracking

- doc/pipeline-details.md
Add diagram and description of pipeline
flow in detail with each client script.
> doc/pipeline-details: add pipeline detailed flow

- doc/overview.md
Add links, fix typos and improve wording of the API overview section.
> doc: update and improve overview section

- api/paginator_models.py
Add 'CustomLimitOffsetParams' class to redefine
limit parameter with custom validations.
> api.paginator_models: add model to redefine limit

- api/main.py
- api/models.py
Fix how the `limit` and `offset` pagination parameters are being handled in the `/nodes` entry point.
> Fix pagination params handling

- api/db.py
- api/main.py
Fixes https://github.com/kernelci/kernelci-api/issues/177
api.db: implement 'Database.count' method
api.main: implement '/count' endpoint
> T37615 Implement '/count' endpoint

- test/conftest.py
- test/test_count_handler.py
test/conftest.py: add fixture `mock_db_count`
test_count_handler: add tests for '/count' endpoint
> T37615 Add unit tests for /count endpoint

- doc/pipeline-details.md
- Update pipeline flow diagram for timeout service.
- Since we have merged checkout and tarball node into a single checkout node, need to update the documentation accordingly.
> T38051 Update "pipeline-details" for timeout and tarball

- api/models.py
Fix a few things in the `Node` model:
* align coding style for all Fields
* drop redundant default value with Optional
* use plain string for default state value
> Node model fixup

- tests/unit_tests/test_user_handler.py
Add test to get user matching provided user ID.
> Add test for GET user endpoint

- doc/_index.md
Update the API overview page with more information and add an embedded Atlas graph with the number of nodes.
> Update API overview page

- doc/design.md
Rename the "overview" page to "design" and update it to match the current state of the API & Pipeline.
> Add design documentation page

- doc/early-access.md
Add a page about the Early Access phase to make it easier for new users to get started.
> doc: add early-access page

- api/main.py
api.main: add PUT '/user/<username>' endpoint
Implement a handler to update user models. Only admin users will be allowed to access this endpoint and be able to
update other user models. All user fields except password can be updated using this handler.
Depends on #353
> Update user model

- doc/early-access.md
Update the Early Access setup documentation page with the reworked kci command line syntax and related TOML settings.
Fixes https://github.com/kernelci/kernelci-core/issues/2158
> doc: update Early Access page with latest kci

- doc/early-access.md
- doc/local-instance.md
Improve documentation of `early-access` and `local-instance` guides.
> doc: improve user-related documentation

- api/main.py
- api/pubsub.py
Introduce GET `/stats/subscriptions` endpoint to get details of existing subscriptions i.e. subscription ID, channel, and owner. Only admin users are allowed to access the endpoint.
> Endpoint to get existing subscriptions GET `/stats/subscriptions`

- env.sample
API sends emails for some user related operations such as verifying user, and password reset.
Add email configuration variable to sample file for environment variables.
> env.sample: add email config variables

- .github/workflows/main.yml
- tests/e2e_tests/conftest.py
- tests/e2e_tests/listen_handler.py
- tests/e2e_tests/test_node_handler.py
- tests/e2e_tests/test_password_handler.py
- tests/e2e_tests/test_pipeline.py
- tests/e2e_tests/test_pubsub_handler.py
- tests/e2e_tests/test_regression_handler.py
- tests/e2e_tests/test_subscribe_handler.py
- tests/e2e_tests/test_unsubscribe_handler.py
- tests/e2e_tests/test_user_creation.py
- tests/e2e_tests/test_user_group_handler.py
Fixes https://github.com/kernelci/kernelci-api/issues/428
> Enable pylint on e2e tests

- docker-compose.yaml
- docker/api/Dockerfile
To test on staging we need to able to set different branch, using environment variables.
Depends on https://github.com/kernelci/kernelci-core/pull/2286
> docker-compose.yaml: Add git repo core_rev

- migrations/20231215122000_node_models.py
Fixes a bug in the migration of regressions (https://github.com/kernelci/kernelci-api/commit/d9176e8724fe25dcaeb56b2b53f983150caed97a)
> migrations: fix regression node migrations

- api/main.py
Depends on https://github.com/kernelci/kernelci-core/pull/2382
API expects `int` values for Node version information. Translate version fields received in the `POST` node handler until we can use it in the pipeline service directly. Due to python version conflicts between core tools and pipeline, we are not able to use the helper function in the pipeline atm.
> api.main: translate node version fields

- api/main.py
Update viewer to correct templates path.
> api/main.py: Update viewer path

- api/templates/viewer.html
Uncaught TypeError: node_data.runtime is undefined
addmiscbuttons https://staging.kernelci.org:9000/viewer?node_id=65df407a9375a6d854fad559:209
onload https://staging.kernelci.org:9000/viewer?node_id=65df407a9375a6d854fad559:256
> viewer: Small bugfixes

- api/main.py
- api/templates/manage.html
Checkout manual submit with job filter will allow to submit jobs for regressions.
> api: Add manage endpoint, checkout manual submit

- api/templates/viewer.html
Many people don't spot what is "->", i should have given it logical name.
> viewer: Add more intuitive name

- api/templates/viewer.html
It is highly useful to see which platform (usuall DUT type) test is scheduled.
> viewer.html: Add to job platform

- .github/workflows/main.yml
- .github/workflows/test.yml
All of sudden workflows are not working anymore,
as docker-compose is missing.
```
Run docker-compose -f test-docker-compose.yaml down
/home/runner/work/_temp/99b8e55a-c49f-4174-934d-3578b404c126.sh: line 1: docker-compose: command not found
Error: Process completed with exit code 127.
```
> fix(workflows): Fix broken workflows

- api/main.py
After we decided that giving superprivileges subtokens is bad idea, we can reuse "submitter" for pipeline API, to identify if node origin is pipeline service, or it is user submission (retry, patchset, etc). This might help to filter some of nodes from going to kcidb, for example.
> feat(api): Repurpose submitter

- api/main.py
- tests/unit_tests/test_node_handler.py
> feat(main): Add treeid field

- api/templates/viewer.html
When we request large amount of data mongo/pagination might be slow, thus we need to show user we are in progress, and it is not a bug, that nothing appeared yet.
> feat(viewer.html): Add modal window to show transfer in progress

- api/main.py
Add basic metrics support for monitoring system, which will be extended further later.
> feat(main): Add metrics endpoint for prometheus

- api/main.py
Add initial implementation of events endpoint
> feat(main.py): Add events endpoint

- api/main.py
While updating some data like kcidb flags we should not generate events, as they will be processed by kcidb bridge again.
> feat(main.py): Add noevent flag

- api/templates/viewer.html
Some divs are showing empty as gray squares on default screen, hide them if they are not used.
> (viewer) Fix small styling mistakes
